# Update these with the right values, then rename to anoixo-staging.yaml
ansible_host: 127.0.0.1
ansible_user: ansible
ansible_ssh_private_key_file: id_rsa

anoixo_username: anoixo
anoixo_password: password

source_abs_dir: /home/anoixo/anoixo
data_abs_dir: /home/anoixo/data
python3: /usr/bin/python3