# Update these with the values you want, then rename to anoixo-staging.yaml

# Information about how to log in to your remote host
ansible_host: 127.0.0.1
server_name: "{{ ansible_host }}"
ansible_user: ansible
ansible_ssh_private_key_file: id_rsa

# Desired usernames and passwords for the Unix users Ansible will create
anoixo_username: anoixo
anoixo_password: password
basex_username: basex
basex_password: password

# Desired usernames and passwords for the BaseX users Ansible will create
basex_server_admin_password: password
basex_server_username: anoixo
basex_server_password: password

# Your ESV API key from https://api.esv.org/
esv_api_key: "Token ffffffffffffffffffffffffffffffffffffffff"

# Where you want your users to be linked to if they click "report a problem", "submit feedback", etc
feedback_form_url: https://forms.gle/fffffffffffffffff

# The username and password to put the app behind (as a security measure)
htpasswd_path: /etc/nginx/.htpasswd
app_auth_username: username
app_auth_password: password

# Desired directories for where Ansible will put the repo, logs, etc
source_abs_dir: /home/anoixo/anoixo
logs_abs_dir: /home/anoixo/logs
basex_data_abs_dir: /home/basex/data
