- name: ensure ubuntu packages
  hosts: staging
  tags: apt
  become: yes
  tasks:
    - name: add key for node PPA
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present

    - name: configure node PPA
      apt_repository:
        repo: deb https://deb.nodesource.com/node_12.x bionic main
        filename: nodesource
        state: present

    - name: install apt packages
      apt:
        pkg: "{{ item }}"
        update_cache: yes
      loop:
        - git
        - nodejs
        - basex
        - python3-venv

- name: create accounts
  hosts: staging
  tags: accounts
  become: yes
  tasks:
    - name: create anoixo user
      user:
        name: "{{ anoixo_username }}"
        password: "{{ anoixo_password | password_hash('sha512') }}"
        shell: /bin/bash
    - name: create basex user
      user:
        name: "{{ basex_username }}"
        password: "{{ basex_password | password_hash('sha512') }}"
        shell: /bin/bash

- name: create basex database user
  hosts: staging
  tags: db
  become: yes
  become_user: "{{ basex_username }}"
  tasks:
    - name: create basex server user
      command: "basex -c 'CREATE USER {{ basex_server_username }} {{ basex_server_password }}'"

- name: setup Nestle Lowfat Treebank database
  hosts: staging
  tags: db
  become: yes
  become_user: "{{ basex_username }}"
  tasks:
    - name: clone treebanks from GitHub
      git:
        repo: "https://github.com/biblicalhumanities/greek-new-testament"
        dest: "{{ basex_data_abs_dir }}/nlf/repo"
        version: master
    - name: create basex database
      command: "basex -c 'SET LANGUAGE el; CREATE DB nestle1904lowfat {{ basex_data_abs_dir }}/nlf/repo/syntax-trees/nestle1904-lowfat/xml/nestle1904lowfat.xml'"
    - name: grant anoixo basex user permission to read the database
      command: "basex -c 'GRANT READ ON nestle1904lowfat TO {{ basex_server_username }}'"

- name: setup basexserver service
  hosts: staging
  tags: db
  become: yes
  tasks:
    - name: install systemd unit file
      template: 
        src: templates/basexserver.service
        dest: /etc/systemd/system/basexserver.service
    - name: have service start on boot, and start it
      service:
        name: basexserver
        enabled: yes
        state: started

- name: clone repository
  hosts: staging
  tags: git, update
  become: yes
  become_user: "{{ anoixo_username }}"
  vars_files:
    - public_vars.yaml
  tasks:
    - name: clone application from GitHub
      git:
        repo: "{{ repo }}"
        dest: "{{ source_abs_dir }}"
        version: master
        force: yes

- name: prepare python
  hosts: staging
  tags: python, update
  become: yes
  become_user: "{{ anoixo_username }}"
  vars_files:
    - public_vars.yaml
  tasks:
    - name: create and populate python venv
      pip:
        virtualenv: "{{ api_abs_dir }}/venv"
        virtualenv_command: "{{ python3 }} -m venv venv"
        requirements: "{{ api_abs_dir }}/requirements.txt"

- name: instantiate private config
  hosts: staging
  tags: config, update
  become: yes
  vars_files:
    - public_vars.yaml
  become_user: "{{ anoixo_username }}"
  tasks:
    - name: create Nestle Lowfat Treebank provider config file for API
      template:
        src: templates/Nestle1904LowfatProvider_Config.py
        dest: "{{ api_abs_dir }}/Nestle1904LowfatProvider_Config.py"
        mode: 0400

- name: build client app
  hosts: staging
  tags: ui, update
  become: yes
  become_user: "{{ anoixo_username }}"
  vars_files:
    - public_vars.yaml
  tasks:
    - name: install node modules for ui
      npm:
        path: "{{ client_abs_dir }}"

    - name: build production ui
      command:
        chdir: "{{ client_abs_dir }}"
        cmd: npm run build