name: Python workflow
on: [push]
jobs:
  test:
    env:
      working-directory: ./server/anoixo-server
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: ${{env.working-directory}}
    - run: |
        python -m pytest
      working-directory: ${{env.working-directory}}