name: Python workflow
on: [push]
jobs:
  test:
    env:
      working-directory: ./server/anoixo-server
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install requirements
      run: |
        pip install -r requirements.txt
      working-directory: ${{env.working-directory}}
    - name: Create secret key file (which needs to be available for import)
      run: |
        mv ESVApiTranslationProvider_Secret_sample.py ESVApiTranslationProvider_Secret.py
      working-directory: ${{env.working-directory}}/translation_providers
    - name: Run tests
      run: |
        pytest
      working-directory: ${{env.working-directory}}