name: TypeScript workflow
on: [push]
jobs:
  test:
    env:
      working-directory: ./client/anoixo-client
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      working-directory: ${{env.working-directory}}
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"
    - name: npm install and test
      working-directory: ${{env.working-directory}}
      run: |
        npm install
        npm test
      env:
        CI: true